### ISSUE TITLE
i have no plugins

### ISSUE THREAD

**Issue by Reycko** [mkdasher/mupen64-rr-lua-#113]
**Describe the bug**
There's no plugins.

**To Reproduce**
1. Start Mupen64
2. No plugins

**Expected behavior**
Pre-installed plugins that are on the source code like GLideN64 and TASInput

**Screenshots**
(I downloaded GLideN64 myself, wasn't here at first)
![image](https://github.com/mkdasher/mupen64-rr-lua-/assets/78082869/1dfaa201-c4cb-431b-acdc-aacae79393f1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Not necessary
 - Version 1.1.3

**Comment by RSw-Why** [comment]
Plugins do not come with Mupen when downloading from this github, aside from TASInput and "gln64" when they updated. Most plugin-based emulators (such as Project64) come with plugins pre-packaged, but this doesnt. I recommend downloading [this](http://repack.skazzy3.com/), which has mupen all set up for you in a folder with a bunch of plugins already.

**Comment by Reycko** [comment]
Oh.
