### ISSUE TITLE
Lua resizing on restart

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#123]
**Describe the bug**
Lua resizing on restart
**To Reproduce**
Open lua script
press reset rom 
and then resizing is permanently messed up in some form until restarting mupen

**Comment by Aurumaker72** [comment]
Closed by [f012645](https://github.com/mkdasher/mupen64-rr-lua-/commit/f0126454d4befc412f1c1f90d8e512c0f56209cc)

ALl scripts get closed on stop now
