### ISSUE TITLE
Allow Bad Roms option doesn't save

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#125]
**Describe the bug**
Doesn't remember this next time mupen is opened.

**To Reproduce**
Open mupen and turn on allow bad roms
close mupen and reopen it

**Comment by Aurumaker72** [comment]
Closed by [c3a7be1](https://github.com/mkdasher/mupen64-rr-lua-/commit/c3a7be1cbfc63004c6a5ec2b012d8cc20d7cd1d7)
