### ISSUE TITLE
Crash when opening setting w/ controller plugged in

### ISSUE THREAD

**Issue by TimeTravelPenguin** [mkdasher/mupen64-rr-lua-#13]
I am using the [Hyperkin N64 Controller](https://www.hyperkin.com/admiral-premium-bt-controller-for-n64r-black-hyperkin.html) with its wireless adaptor. When Using the TAS controller plugin, opening a ROM or the controller settings crashes the application. If I use Jabo's controller plugin, it works fine. 

Unsure if this is due to Mupen or the plugin, but I thought I should report it for investigation, should it be an issue on Mupen's side.

**Comment by Aurumaker72** [comment]
Dead link

**Comment by Aurumaker72** [comment]
Fixed* in de8f3031fc797a03acb30f62937a3939f304c999
