### ISSUE TITLE
Potential deadlock in closeRom

### ISSUE THREAD

**Issue by Aurumaker72** [mkdasher/mupen64-rr-lua-#130]
# Summary
The emulator thread, and thereby the closeRom thread, can hang after resuming the game in `closeRom`

# Related Issue
#97

**Comment by crackhex** [comment]
Mostly fixed with [this commit](https://github.com/mkdasher/mupen64-rr-lua-/commit/6471100a39c541c1abad8b89b666bc334e254e2f)

**Comment by crackhex** [comment]
Fixed with [this commit](https://github.com/mkdasher/mupen64-rr-lua-/commit/536640460adea7207fb6fdf7a0268a91a74fdacf)
