### ISSUE TITLE
Lua flickers when running multiple scripts

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#131]
**Describe the bug**
Ran inputlua and recording ghost together, and the inputlua started flickering badly.

**Comment by Aurumaker72** [comment]
Example scripts
[sm64expert_2.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/12812304/sm64expert_2.zip)
[recordghost.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/12812305/recordghost.zip)

**Comment by Aurumaker72** [comment]
Closed by [d56564e](https://github.com/mkdasher/mupen64-rr-lua-/commit/d56564ebbe6203f97253260bdf1965ce3f0aacc7)

**Comment by crackhex** [comment]
[tastimer_v0_2_1.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/12839999/tastimer_v0_2_1.zip)

Still flickers with this one.

**Comment by Aurumaker72** [comment]
Closed by [c838df2](https://github.com/mkdasher/mupen64-rr-lua-/commit/c838df2c26924a077e2bc71619dd6b015943bc66)
