### ISSUE TITLE
File Dialogs trap execution if opened after emulator has started

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#132]
**Describe the bug**
Browse doesn't work for Lua Dialogue when Game running- it freezes mupen and makes it unresponsive

**To Reproduce**
Open any rom
Open lua dialogue 
browse: gog

**Comment by Aurumaker72** [comment]
Shell API bug, I asked some experts hopefully we get insight

**Comment by Aurumaker72** [comment]
Closed by [42dfc9d](https://github.com/mkdasher/mupen64-rr-lua-/commit/42dfc9df73dc5335b70031ddb828cddb94287c4a)
