### ISSUE TITLE
Movie recording start/stop menu items don't get correctly updated

### ISSUE THREAD

**Issue by Aurumaker72** [mkdasher/mupen64-rr-lua-#138]
# Summary
Movie recording start/stop menu items don't get correctly updated after starting a movie, making it impossible to stop the movie recording

# Repro

1. Start movie recording
2. Check the menu items
3. 
![grafik](https://github.com/mkdasher/mupen64-rr-lua-/assets/48759429/f6194fc9-314a-468f-ae3d-30cffe54e3a0)

**Comment by crackhex** [comment]
Fixed with with [cf94ad91c68b025ac87dfbf1d42b5e14ab18f703](https://github.com/mkdasher/mupen64-rr-lua-/commit/cf94ad91c68b025ac87dfbf1d42b5e14ab18f703)
