### ISSUE TITLE
Roms don't start up with gln

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#140]
If loading up a rom using the gln or bettergln plugins, the core fails to start and it hangs on a black screen. Not sure which commit caused this.

(discovered by @onlymx13)

**Comment by crackhex** [comment]
Caused by [This commit](https://github.com/mkdasher/mupen64-rr-lua-/commit/5855c824b4152eff275cb546cdaa466fc73e3b8b)

**Comment by Aurumaker72** [comment]
Some cursory analysis shows that the emu thread is waiting for a [resize message](https://github.com/Madghostek/better-gln64/blob/84180e3ed09a5e7191b2a2d9d3050a6dac27208a/OpenGL.cpp#L179) to arrive on the UI thread, while the UI thread is waiting for the emu thread to start.

This is a deadlock and thus the emu will never start.

**Comment by Aurumaker72** [comment]
Closed by [419eff8](https://github.com/mkdasher/mupen64-rr-lua-/commit/419eff8cc0b9d96cc07394f415a3845ee1e377e4)
