### ISSUE TITLE
 Movie Recording doesn't work correctly with Existing Savestate

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#142]
**Describe the bug**
If "Allow Bad Roms" is selected, then the existing savestate function of the record dialogue malfunctions. It records the m64 to the st after misreading the st or something.

Repro:
Open Mupen64.exe
Open any rom, and check allow Bad Roms
Try recording from existing savestate, it will overwrite the savestate with the movie data

**Comment by Aurumaker72** [comment]
Closed by [1ee5b7e](https://github.com/mkdasher/mupen64-rr-lua-/commit/1ee5b7e13c4d9867b74e0d5a0ead055295acfa66)
