### ISSUE TITLE
Recent freeze buttons don't prevent items from being added

### ISSUE THREAD

**Issue by Aurumaker72** [mkdasher/mupen64-rr-lua-#146]
# Summary
Recent freeze buttons don't prevent items from being added

# Reproduction

1. Check a "Freeze" menu item
2. Perform the associated adding action (e.g.: loading a rom)
3. Check the recent list

# Expected

The item isn't added

**Comment by crackhex** [comment]
Fixed with https://github.com/mkdasher/mupen64-rr-lua-/commit/ad245a7e40536c799718c3b2535112a1ebf85401
