### ISSUE TITLE
Rombrowser and plugins don't refresh correctly after changing/adding directory

### ISSUE THREAD

**Issue by Aurumaker72** [mkdasher/mupen64-rr-lua-#148]
# Repro

1. Add a new rombrowser source directory
2. Refresh rombrowser

**Comment by RSw-Why** [comment]
this issue also applies to changing plugin directory, not tested but probably the other directories too.

**Comment by Aurumaker72** [comment]
Investigation shows that correct paths are passed into `FindFirstFile` (inside `get_files_with_extension_in_directory`), but no values are returned.

I don't know what to do about this.

**Comment by Aurumaker72** [comment]
Closed by c326cf8db78abc250b112a3f81a82e7cab6efaad

This issue was a doozy: combination of subtle wstring conversion incorrectness and ref assignment
