### ISSUE TITLE
forced to close mupen after opening a "bad rom" with allow bad roms off.

### ISSUE THREAD

**Issue by RSw-Why** [mkdasher/mupen64-rr-lua-#151]
opening a rom with a large file (such as senseless delirium: https://sm64romhacks.com/patch/Super_Mario_Senseless_Delirium_03.zip with "allow bad roms" off in settings, produces intended popup "failed to open rom", upon clicking "ok" it tries loading anyways, and produces a new popup saying "an error has occurred". pressing retry does nothing, pressing close closes mupen.

https://github.com/mkdasher/mupen64-rr-lua-/assets/65158808/3437688f-c3e3-490a-8cf5-f0b301564757

**Comment by crackhex** [comment]
https://github.com/mkdasher/mupen64-rr-lua-/commit/a585b78aee505871a9ef6b2b87109f9116677dae fixed with this commit
