### ISSUE TITLE
mupen not showing recent lua scripts

### ISSUE THREAD

**Issue by RSw-Why** [mkdasher/mupen64-rr-lua-#153]
Lua scripts run but are not saved to "recent scripts" list0

**To Reproduce**
1. Load lua script like normal
2. go to lua script -> recent scripts
3. no scripts are shown

**Expected behavior**
scripts are shown for quick and easy access to lua scripts

![image](https://github.com/mkdasher/mupen64-rr-lua-/assets/65158808/2939a2e7-2a3c-466f-a20e-beb7bf4272e2)

Edit: Load latest script also does nothing.

**Comment by crackhex** [comment]
fixed with [2126645](https://github.com/mkdasher/mupen64-rr-lua-/commit/2126645551a2065eccb409b499522b42c088ae84)
