### ISSUE TITLE
Statusbar randomly disappears

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#154]
On emulator reset, sometimes the statusbar can disappear. 

Not sure what causes this, maybe will look into it some time soon.

**Comment by Aurumaker72** [comment]
Pending confirmation that it's not fixed by [b8999a1](https://github.com/mkdasher/mupen64-rr-lua-/commit/b8999a1465834985d1b428cc4af2a00b0efc18fb)

**Comment by crackhex** [comment]
Doesn't happen anymore from what I know, will close.
