### ISSUE TITLE
Lua scripts don't re-minimise when being reloaded

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#155]
The windows will respawn from being minimised and will pop up, which can be rather annoying to deal with when restarting movie a bunch of times 
Not really a bug, just a consequence of not having implemented this intentionally

**Comment by Aurumaker72** [comment]
Closed by [c742f8f](https://github.com/mkdasher/mupen64-rr-lua-/commit/c742f8f97a2d496341ee72ea01c5ae9ea8cb0a46)
