### ISSUE TITLE
bottom black bar disappearing

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#157]
When resetting the emu, the bottom of the screen gets covered up by the statis bar. The black bar at the bottom disappears.
Repro:
Open a rom
- Open settings, click other window capture and uncheck, or some other various actions
-close settings and then reset emu

**Comment by Aurumaker72** [comment]
Closed by [b8999a1](https://github.com/mkdasher/mupen64-rr-lua-/commit/b8999a1465834985d1b428cc4af2a00b0efc18fb)
