### ISSUE TITLE
Prevent scrolling to top when hotkey is assigned

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#166]
**Describe the bug**
The bug occurs when a hotkey is assigned, the dialogue refreshes and sends the user back to the top of the hotkey list.

**To Reproduce**
1. Go to 'Hotkeys'
2. Click on any hotkey
3. Assign value to hotkey
4. Observe the scrolling back to the top phenomenon

**Expected behavior**
Instead of restarting the user back at the top of the list, it would be expected to be able to stay where the user previously was on the list, to be able to continue assigning future hotkeys with more relative ease.

**Additional context**
This is not much of an annoyance unless continually assigning hotkeys. Adding it as a "medium" priority issue.

**Comment by Aurumaker72** [comment]
Closed by 5a5d2dfad00296f8871827e26fe2f1b0b240ebea

It remembers and advances selection after hotkey assignment, so it's less annoying when assigning hotkeys in sequence
