### ISSUE TITLE
Emulation speed inaccuracy adversely affects normal playback

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#167]
**Describe the bug**
After a recent introduction to a different timer system for mupen, accuracy in the speed of playback has fallen. The fps will often hover around 27fps instead of the intended fixed 30fps, and is subject to change depending on various factors. It makes watching runs on normal speed not very possible, or for playing RTA.

**To Reproduce**
1. Launch a rom
2. Observe the FPS counter not being at 30fps

**Expected behavior**
The fps counter should stay at almost exactly 30fps, since that is around what its intended fps is for playing back the emulation normal speed.

**Additional context**
Bug pertaining to accuracy of emulation playback, adding as high priority bug.

**Comment by Aurumaker72** [comment]
Closed by dbb0ff9c31aeadb19f0f410e89d038ccf571c503
