### ISSUE TITLE
An error message popping up when unable to load a savestate

### ISSUE THREAD

**Issue by anonymous7002** [mkdasher/mupen64-rr-lua-#18]
When you try to load a savestate which hasn't been saved yet, it pops up an error message which pauses the game and which I have to close. Just show it in the status bar!

**Comment by Aurumaker72** [comment]
No, no one would read it then get confused why it didnt work

**Comment by anonymous7002** [comment]
But the message box popping up is so annoying!

**Comment by Aurumaker72** [comment]
Close this maybe? (Feature was added)
