### ISSUE TITLE
Disable lua scripts when rom is closed

### ISSUE THREAD

**Issue by crackhex** [mkdasher/mupen64-rr-lua-#181]
**Describe the bug**
Sometimes when running a lua script when a rom is not running, DWM explodes and causes purple graphic to spawn for brief period of time

**To Reproduce**
Open Mupen
Open SM64Lua.lua
Observe behaviour

**Comment by Aurumaker72** [comment]
Can't repro on 99417ab8deb8bcf7f65adead012d30b197519f84

**Comment by Aurumaker72** [comment]
This doesn't seem to happen anymore, and lua scripts are now allowed to run when emulation is stopped.
