### ISSUE TITLE
loading a corresponding rom automatically when playing back a movie file

### ISSUE THREAD

**Issue by irimuri** [mkdasher/mupen64-rr-lua-#185]
**Is your feature request related to a problem? Please describe.**
Choosing the correct rom to play back a movie file can be difficult and time consuming when you have a lot of roms to sift through.

**Describe the solution you'd like**
If you load a movie file that doesn't match with the rom you're on, the program loads up the correct rom and play it back normally.
Similarly, if you have no rom currently loaded and try to play a movie file, the program loads up the correct rom and start a playback.

**Comment by Aurumaker72** [comment]
This feature already exists (79fc31d639874b799ce3f28ca36f7d47bfb9cb2e) and will be available in 1.1.7
