### ISSUE TITLE
Runner

### ISSUE THREAD

**Issue by Aurumaker72** [mkdasher/mupen64-rr-lua-#192]
# Summary

Universal browser with various recent files

# Concept

![grafik](https://github.com/mkdasher/mupen64-rr-lua-/assets/48759429/c5d50553-5dba-4b04-832b-863b63e4be8b)

# Workflow

`Ctrl + P` or `Utilites > Runner...` opens the Runner dialog

**Comment by RSw-Why** [comment]
I think that something like this could be nicer to look at/use:
![image](https://github.com/mkdasher/mupen64-rr-lua-/assets/65158808/704e80a9-3320-46b3-89ad-1805ec81ea0f)
Im not a dev though so Im not sure on if this is unreasonable or nah

**Comment by Aurumaker72** [comment]
Closed by 5f67d2abe1724de3c7fdbb38daa677c5e7e11d91
