### ISSUE TITLE
Mupen 1.0.9 Not Work in LuaRedux-master

### ISSUE THREAD

**Issue by SM64TASVideo** [mkdasher/mupen64-rr-lua-#204]
![Screenshot 2024-06-18 122254 error](https://github.com/mkdasher/mupen64-rr-lua-/assets/149284765/936c7bf2-9a6a-4970-aad2-0eb9c0c7d3ff)

ext.72: attempt to index a nil value (global 'd2d')

**Comment by Aurumaker72** [comment]
SM64 Lua Redux requires Mupen64 1.1.5 or newer. This issue pertains to SM64 Lua Redux, not mupen.
