### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by SM64TASVideo** [mkdasher/mupen64-rr-lua-#207]
GPU Is: Intel IRIS XE Graphics

Graphics: jabo's direct3d8 1.6.1

**Describe the bug**
Access Violation Error is: While processing graphics data an exception occurred, you may need to restart the emulator

**Expected behavior**
Access Violation Error

**Screenshots**

![Screenshot 2024-07-14 205502](https://github.com/user-attachments/assets/429f418e-eec5-4263-bc8a-8691a0f32274)

**Comment by SM64TASVideo** [comment]
This Is Why Runtime For Error, Where you need to restart the emulator?

**Comment by Aurumaker72** [comment]
We generally can't provide support for Jabo's Direct3D8 as its source code isn't available, and the error message being this cryptic certainly doesn't help.

I suggest updating your graphics drivers and trying again.

If you can, however, don't use Jabo's Direct3D8. Use the currently supported [better-gln64](https://github.com/Madghostek/better-gln64/releases/tag/1.2) instead.
