### ISSUE TITLE
Could Not Find This Any Files M64 (Mupen64 1.1.7)

### ISSUE THREAD

**Issue by SM64TASVideo** [mkdasher/mupen64-rr-lua-#214]
https://github.com/user-attachments/assets/a8093792-92f9-4b45-9dba-ab1b449e2d01

Where Files M64

**Comment by SM64TASVideo** [comment]
Playing SM64 TSYS

**Comment by Aurumaker72** [comment]
Hi, thank you for the report.

Could you please clarify what exactly the issue is?

If it pertains to the location of recorded m64s being unclear, try checking your recent movies menu. Your recently recorded and played movies will be visible and perhaps you'll find the m64 there.

**Comment by Aurumaker72** [comment]
Since this issue has been inactive for 3 weeks and no further information was provided, it will be closed. Feel free to reopen after giving additional information.
