### ISSUE TITLE
Playback rerecording

### ISSUE THREAD

**Issue by TimeTravelPenguin** [mkdasher/mupen64-rr-lua-#3]
Currently Eddio in the TAS community is working on a LUA script to record a movie to a new m64/st file for splitting full game runs into ILs. I was wondering if this can be implemented in-application? It would be significantly easier to implement, I feel, than doing some hacky LUA.

**Comment by Madghostek** [comment]
I'm not sure if implementing this in mupen is a good idea, because in the end mupen is still a n64 emulator, not sm64-only tool, so it would be weird to have such option just for one game. And apart from file splitting, lua already gives semi good interface to work with this I think.
