### ISSUE TITLE
.sfc (SNES ROMs) detected by Mupen as N64 ROMs and show up in the ROMs list

### ISSUE THREAD

**Issue by SnkaeSael** [mkdasher/mupen64-rr-lua-#37]
**Describe the bug**
Mupen64 shows .sfc files (interestingly only Super Mario World and Super Mario Kart, both of which are 512KB) in the list of ROMs when you open the application.

**To Reproduce**
Get an SNES ROM and place it in the folder Mupen looks for ROMs in (only 512KB ROMs, like Super Mario World seem to work), then open Mupen64

**Expected behavior**
A list of .z64, .n64, and .v64 ROMs appear in the list

**Screenshot**
![image](https://user-images.githubusercontent.com/66127672/129073477-284f0563-088e-483e-91da-e060c280a48c.png)

**Version info**
Windows 10 Home 64bit build 19043 (21H1)
Mupen64 release v1.0.8

**Comment by Aurumaker72** [comment]
Ok

**Comment by Aurumaker72** [comment]
Cannot reproduce this issue on 1.0.9.
Did you disable "Manage Bad Roms"?

**Comment by SnkaeSael** [comment]
No, I have all alerts enabled under Settings > General

**Comment by SnkaeSael** [comment]
No idea how to do that lol

**Comment by Aurumaker72** [comment]
[latest_mupen.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/6970404/latest_mupen.zip)

**Comment by SnkaeSael** [comment]
Still occurs in v1.0.9

**Comment by SnkaeSael** [comment]
![image](https://user-images.githubusercontent.com/66127672/129079377-de373b02-a9a1-484d-aacd-a26ea1c98619.png)

**Comment by SnkaeSael** [comment]
Try to get a US Super Mario World ROM

**Comment by Aurumaker72** [comment]
Can you please provide:
- exact issue reproduction steps
- your mupen64.cfg file

Also try deleting your mupen cache file mupen64.cch

**Comment by Aurumaker72** [comment]
> Try to get a US Super Mario World ROM

I tried but it doesnt seem to work

**Comment by SnkaeSael** [comment]
**Reproduction**
Obtain a Super Mario World ROM, and move it to one of your ROM directories. Refresh the list of ROMs and you should see Super Mario World.
I cannot be any more clear than that

**Config**
[mupen64cfg.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/6970470/mupen64cfg.zip)

**Comment by Aurumaker72** [comment]
I'm unable to reproduce this issue on my machine. Mind joining the discord server?

**Comment by SnkaeSael** [comment]
sure

**Comment by SnkaeSael** [comment]
closing cuz it was just that my roms had 40 (in hex) as the first byte

**Comment by Aurumaker72** [comment]
Issue has been resolved in commit 1249eb87f0ee6aa90ab2b2ef646ffc680ab49ca8
