### ISSUE TITLE
"Unknown country code" warning pops up repeatedly during AVI capture

### ISSUE THREAD

**Issue by despoa** [mkdasher/mupen64-rr-lua-#48]
When trying to capture AVI for a game whose country code is unknown (usually prototypes), the warning box saying `[VCR]: Warning - unknown country code, using 60 FPS for video.` pops up for every frame captured and has to be closed manually. An example game is Wildwaters: Extreme Kayak.

```
ROM Filename: Wildwaters (USA) (Proto) (1999-06-15).z64
CRC32: 40443C67
MD5: B867880C96C9E8D3130DDE5526C95439
SHA-1: 3FF76B30A9179F1AC116CC04D560CE333DB443AF
```

**Comment by Aurumaker72** [comment]
Fixed in 435a58394c3e8a27a6e173e3ef31c4c706188dc1
