### ISSUE TITLE
SHADOWXFM FEATURE , by shadoXFM

### ISSUE THREAD

**Issue by suttynhoe** [mkdasher/mupen64-rr-lua-#63]
ShadoXFM — Hoje às 16:48
too hard
everyrhing is circle
make wgui.rectwithcirclecorner

golden cosita 🧐 — Hoje às 16:52
post it as issue on github
golden cosita 🧐 — Hoje às 16:52
or i will forgey

**Comment by Aurumaker72** [comment]
Implemented in 5ebb91f585f68c95c6b4ddd8dfc98cce362a7104
